name: Smarket
description: Graduation project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.0
  credit_card_scanner: ^1.0.5
  cupertino_icons: ^1.0.2
  dio: ^5.2.1
  easy_splash_screen: ^1.0.4
  email_otp: ^1.0.4
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage_web: ^1.1.1
  flutter_svg: ^1.1.6
  get: ^4.6.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: any
  keyboard_service: ^2.0.2
  native_pdf_renderer: ^5.0.0+1
  open_file: ^3.2.1
  path: ^1.8.2
  path_provider: ^2.0.12
  pdf: ^3.9.0
  pin_code_fields: ^7.4.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.20
  text_scroll: ^0.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.9
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
    - assets/products/

  fonts:
    - family: harabara
      fonts:
        - asset: assets/fonts/HarabaraMais.otf
    - family: harabaraBold
      fonts:
        - asset: assets/fonts/Harabara_Mais_Bold.otf
    - family: harabaraBlack
      fonts:
        - asset: assets/fonts/Harabara_Mais_Black.otf
    - family: open
      fonts:
        - asset: assets/fonts/open.ttf
    - family: star
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
